CREATE TABLE AUTHOR
(
    ID BIGINT AUTO_INCREMENT PRIMARY KEY NOT NULL,
    NAME VARCHAR(255),
    LINK VARCHAR(255)
);
CREATE TABLE CUSTOMER
(
    ID BIGINT AUTO_INCREMENT PRIMARY KEY NOT NULL,
    NAME VARCHAR(255)
);
CREATE TABLE CUSTOMER_AUTHOR
(
    CUSTOMER_ID BIGINT NOT NULL,
    AUTHOR_ID BIGINT NOT NULL,
    PRIMARY KEY (AUTHOR_ID, CUSTOMER_ID)
);
CREATE TABLE CUSTOMER_UNREAD_WRITING
(
    CUSTOMER_ID BIGINT NOT NULL,
    WRITING_ID BIGINT NOT NULL,
    PRIMARY KEY (WRITING_ID, CUSTOMER_ID)
);
CREATE TABLE USER_DATA
(
    ID BIGINT AUTO_INCREMENT PRIMARY KEY NOT NULL,
    ENABLED BOOLEAN,
    PASSWORD VARCHAR(255),
    ROLE VARCHAR(255),
    USERNAME VARCHAR(255),
    CUSTOMER_ID BIGINT
);
CREATE TABLE VERIFCATION_DATA
(
    ID VARCHAR(255) PRIMARY KEY NOT NULL,
    EXPIRATION_DATE TIMESTAMP,
    USER_ID BIGINT
);
CREATE TABLE WRITING
(
    ID BIGINT AUTO_INCREMENT PRIMARY KEY NOT NULL,
    NAME VARCHAR(255),
    DESCRIPTION VARCHAR(4096),
    GROUP_NAME VARCHAR(255),
    LAST_CHANGED_DATE TIMESTAMP,
    LINK VARCHAR(255),
    PREV_SIZE VARCHAR(255),
    SIZE VARCHAR(255),
    AUTHOR_ID BIGINT
);
CREATE UNIQUE INDEX UK_I2XI9SA37P682Y01NA0OFHCN4_INDEX_7 ON AUTHOR (LINK);
CREATE UNIQUE INDEX UK_CRKJMJK1OJ8GB6J6T5KT7GCXM_INDEX_5 ON CUSTOMER (NAME);
ALTER TABLE CUSTOMER_AUTHOR ADD FOREIGN KEY (AUTHOR_ID) REFERENCES AUTHOR (ID);
ALTER TABLE CUSTOMER_AUTHOR ADD FOREIGN KEY (CUSTOMER_ID) REFERENCES CUSTOMER (ID);
CREATE INDEX FK_1S9PUOHMGWECP0T8WUSY7OHSS_INDEX_1 ON CUSTOMER_AUTHOR (AUTHOR_ID);
CREATE INDEX FK_4EBQYLNO2PQPIWAYAL6GD61HT_INDEX_1 ON CUSTOMER_AUTHOR (CUSTOMER_ID);
ALTER TABLE CUSTOMER_UNREAD_WRITING ADD FOREIGN KEY (CUSTOMER_ID) REFERENCES CUSTOMER (ID);
ALTER TABLE CUSTOMER_UNREAD_WRITING ADD FOREIGN KEY (WRITING_ID) REFERENCES WRITING (ID);
CREATE INDEX FK_C6VRTJS25ELP9GB8P7UJHS30P_INDEX_D ON CUSTOMER_UNREAD_WRITING (WRITING_ID);
CREATE INDEX FK_SB80GE8W5UHYNEQX5HI8P9YD7_INDEX_D ON CUSTOMER_UNREAD_WRITING (CUSTOMER_ID);
ALTER TABLE USER_DATA ADD FOREIGN KEY (CUSTOMER_ID) REFERENCES CUSTOMER (ID);
CREATE INDEX FK_VQ6QHQFGEC6G6I8SU26SEGR2_INDEX_B ON USER_DATA (CUSTOMER_ID);
ALTER TABLE VERIFCATION_DATA ADD FOREIGN KEY (USER_ID) REFERENCES USER_DATA (ID);
CREATE INDEX FK_SF5TOBO46794CUFO1CQI6EQQO_INDEX_9 ON VERIFCATION_DATA (USER_ID);
ALTER TABLE WRITING ADD FOREIGN KEY (AUTHOR_ID) REFERENCES AUTHOR (ID);
CREATE INDEX FK_KFDAVNCD8JDATAVXTS9D1Q9D7_INDEX_8 ON WRITING (AUTHOR_ID);

